theme: jekyll-theme-minimal
title: [Xreader App]
logo: /assets/img/logo.png
description: [A short description of your site's purpose]
github:
  zip_url: http://example.com/download.zip
  another_url: another value
