theme: jekyll-theme-minimal
title: [Xreader App]
logo: /assets/img/logo.png
show_github: [false]
description: [Xreader allows you stay tuned for latest articles and news related to Swift development.]
github:
  zip_url: http://example.com/download.zip
  another_url: another value
